[package]
name = "rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "advent_of_code"
path = "src/lib.rs"

[dependencies]
itertools = "0.10.1"
